---
title: "Visualisations"
author: "Harmonic Analytics"
date: "26/03/2021"
output: html_document
---

```{r, setup, include=FALSE}
library(RSQLite)
library(tidyverse)
library(audio)
library(shiny)
library(shinyjs)

source("app/helpers/metadata.R")
source("app/helpers/musicTheoryFuncs.R")
source("app/helpers/noteGeneration.R")
source("app/helpers/playMusic.R")
source("app/helpers/waveGeneration.R")

filename <- "app/data/wjazzd.db"
sqlite.driver <- dbDriver("SQLite")
db <- dbConnect(sqlite.driver,
                dbname = filename)

tables = list()
for (table in dbListTables(db)) {
  tables[[table]] = dbReadTable(db, table)
}

# Import the midi note table
midiNoteTable = read_csv("app/data/midiNoteTable.csv")
scaleDegrees = read_csv("app/data/scaleDegrees.csv")
enharmonicNotes = read_csv("app/data/enharmonicNotes.csv")
```

# meta plots
```{r}
spicyTable = tables$melody %>%
  left_join(tables$solo_info, by=c("melid")) %>%
  mutate(keyRoot = strsplit(key, "-")[[1]][1]) %>%
  left_join(tables$beats, by=c("melid", "bar", "beat")) %>%
  left_join(midiNoteTable, by=c("pitch"="MIDI Note")) %>%
  mutate(chord=ifelse(chord=="", NA, chord)) %>%
  fill(chord, .direction="down") %>%
  rowwise() %>%
  mutate(spiciness = getSpiciness(chord, Note)) %>%
  mutate(spicinessDuration = spiciness*duration)

spicyTable2 = spicyTable %>% left_join(tables$track_info, by=c("trackid")) 

normalisedSpiciness = spicyTable2 %>%
  group_by(melid) %>%
  summarise(totalSpiciness=sum(spiciness, na.rm=T),
            totalDuration=max(onset.x)-min(onset.x),
            performer=performer[1],
            title=title[1],
            recordingdate=recordingdate[1],
            numNotes = n()) %>%
  mutate(normalisedSpiciness=totalSpiciness/numNotes,
         noteRate = numNotes/totalDuration) %>%
  rowwise() %>%
  mutate(recordingYear = as.numeric(getYear(recordingdate)))

plotly::ggplotly(normalisedSpiciness %>%
  ggplot(aes(x=recordingYear, y=normalisedSpiciness, fill=title, colour=performer)) + 
  geom_jitter())

artistSpiciness = normalisedSpiciness %>%
  group_by(performer) %>%
  summarise(avgNormalisedSpiciness=mean(normalisedSpiciness),
            avgNoteRate = mean(noteRate),
            avgRecordingYear = mean(recordingYear))

plotly::ggplotly(artistSpiciness %>%
  ggplot(aes(x=avgRecordingYear, y=avgNormalisedSpiciness, colour = performer)) + 
  geom_jitter() +
  scale_y_continuous(limits=c(0.75, 1.4)))

```

```{r}
getYear = function(dateStr) {
  dateStr1 = strsplit(dateStr, "[.]")
  for (num in dateStr1[[1]]) {
    if (nchar(num)==4) {
      return(num)
    }
  }
  dateStr1 = strsplit(dateStr, "-")
  for (num in dateStr1[[1]]) {
    if (nchar(num)==4) {
      return(num)
    }
  }
  
  dateStr1 = strsplit(dateStr, " ")
  for (num in dateStr1[[1]]) {
    if (nchar(num)==4) {
      return(num)
    }
  }
  
  return(NA)
}

```

```{r}
# Load package
# devtools::install_github("mattflor/chorddiag")
library(chorddiag)

noteSuccession = tables$melody %>%
  filter(melid==1) %>%
  left_join(midiNoteTable, by=c("pitch"="MIDI Note")) %>%
  select("Note") %>%
  rowwise() %>%
  mutate(Note = convertToKeyEnharmonic(Note, "Bb")) %>%
  ungroup() %>%
  mutate(nextNote = lead(Note)) %>%
  filter(!is.na(nextNote)) %>%
  count(Note, nextNote) 

notes = unique(c(noteSuccession$Note, noteSuccession$nextNote))


notes = c("Bb", "F", "C", "G","D", "A", "E", "B", "F#", "Db", "Ab", "Eb")

m = matrix(0, nrow=length(notes), ncol=length(notes))
dimnames(m) <- list(from = notes, to = notes)

for (i in 1:nrow(noteSuccession)) {
  m[noteSuccession[[i, "Note"]], noteSuccession[[i, "nextNote"]]] = noteSuccession[[i, "n"]]
}

groupColors=c(viridisLite::plasma(7), rev(viridisLite::plasma(6)[2:6]))

# Build the chord diagram:
p <- chorddiag(m, groupnamePadding = 20, showTicks = F, groupColors = groupColors)
p
```
